[package]
name = "zed_gitlab-duo"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/gitlab.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.1.0"
